# Generated by Django 3.2.15 on 2022-09-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='category',
            new_name='jobcategory',
        ),
    ]
